---
# tasks file for tomcat
- name: Installing_java
  apt:
    name: default-jdk
    state: present
    update_cache: yes
- name: Download_tomcat
  get_url:
    url: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.98/bin/apache-tomcat-8.5.98.tar.gz"
    dest: /tmp/apache-tomcat-8.5.98.tar.gz
- name: Extracting_tomcat
  ansible.builtin.unarchive:
    src : /tmp/apache-tomcat-8.5.98.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/apache-tomcat-8.5.98.tar.gz
    owner: root
    group: root
    mode: 0755
- name: changes_in_webapps
  shell: sed -i 's/8080/8082/g' /opt/apache-tomcat-8.5.98/conf/server.xml && sed -i  '21s/^/<!--/g' "/opt/apache-tomcat-8.5.98/webapps/host-manager/META-INF/context.xml" && sed -i  '22s/$/-->/g' "/opt/apache-tomcat-8.5.98/webapps/host-manager/META-INF/context.xml" && sed -i  '21s/^/<!--/g' "/opt/apache-tomcat-8.5.98/webapps/manager/META-INF/context.xml" && sed -i  '22s/$/-->/g' "/opt/apache-tomcat-8.5.98/webapps/manager/META-INF/context.xml" && sed -i -e '55 a\<role rolename="manager-gui" /> \n<user username="harsha" password="1234" roles="manager-gui" /> \n<!-- user admin can access manager and admin section both --> \n<role rolename="admin-gui" /> \n<user username="harsha" password="1234" roles="manager-gui, admin-gui" />' "/opt/apache-tomcat-8.5.98/conf/tomcat-users.xml"
- name: shutdown_start
  become: true
  shell: cd /opt/apache-tomcat-8.5.98/bin/ && ./shutdown.sh && sleep 5 && ./startup.sh 
